_home:
  pattern: /
  defaults: { _controller: HectorFoodServiceBundle:Meal:index }
  
_meal:
  resource: "@HectorFoodServiceBundle/Controller/MealController.php"
  type:     annotation
  prefix:   /meal

_item:
  resource: "@HectorFoodServiceBundle/Controller/ItemController.php"
  type:     annotation
  prefix:   /item

_measuring:
  resource: "@HectorFoodServiceBundle/Controller/MeasuringController.php"
  type:     annotation
  prefix:   /measuring

_chart:
  resource: "@HectorFoodServiceBundle/Controller/ChartController.php"
  type:     annotation
  prefix:   /chart
